apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    name: nginx-test-rc
spec:
  replicas: 1
  selector:
    app: nginx-test-rc
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-test-rc
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
